### ISSUE TITLE
Error in building: addon_rbdl

### ISSUE THREAD

**Issue by salvato** [wcaarls/grl#16]
Scanning dependencies of target addon_rbdl
[ 92%] Building CXX object CMakeFiles/addon_rbdl.dir/addons/rbdl/src/rbdl.cpp.o
/home/rov/grl/addons/rbdl/src/rbdl.cpp:34:10: fatal error: rbdl/addons/luamodel/luamodel.h: File o directory non esistente
 #include <rbdl/addons/luamodel/luamodel.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/addon_rbdl.dir/build.make:62: recipe for target 'CMakeFiles/addon_rbdl.dir/addons/rbdl/src/rbdl.cpp.o' failed
make[2]: *** [CMakeFiles/addon_rbdl.dir/addons/rbdl/src/rbdl.cpp.o] Error 1
CMakeFiles/Makefile2:619: recipe for target 'CMakeFiles/addon_rbdl.dir/all' failed
make[1]: *** [CMakeFiles/addon_rbdl.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by salvato** [comment]
Just to add some more information, this is the output from cmake

rov@rov-P553UJ:~/grl/build$ cmake ..
-- The C compiler identification is GNU 8.4.0
-- The CXX compiler identification is GNU 8.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Set default build type: RelWithDebInfo
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'eigen3'
--   Found eigen3, version 3.3.4
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Found Lua51: /usr/lib/x86_64-linux-gnu/liblua5.1.so;/usr/lib/x86_64-linux-gnu/libm.so (found version "5.1.5") 
-- Building Lua deployer
-- Building included YAML library
patching file CMakeLists.txt
-- Performing Test FLAG_WEXTRA
-- Performing Test FLAG_WEXTRA - Success
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Building included ICS library
-- Checking for module 'rbdl>=2.4.0'
--   Found rbdl, version 2.6.0
-- Found Eigen3: /usr/include/eigen3 (Required is at least version "3.0.0") 
-- ZeroMQ version: 4.2.5
-- Found ZeroMQ: /usr/include (found suitable version "4.2.5", minimum required is "4.0.0") 
-- Building included CPPZMQ and ZMQ_MESSENGER library
-- Found PythonInterp: /usr/bin/python3.6 (found version "3.6.9") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so
-- Performing Test HAS_CPP14_FLAG
-- Performing Test HAS_CPP14_FLAG - Success
-- pybind11 v2.3.dev0
-- Build type: RelWithDebInfo
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so   
-- Found GLFW: /usr/lib/x86_64-linux-gnu/libglfw.so  
-- GLFW found: /usr/lib/x86_64-linux-gnu/libglfw.so -- /usr/include
-- Found Doxygen: /usr/local/bin/doxygen (found version "1.8.15") found components:  doxygen dot 
** Building OpenGL addon
-- Found FreeGLUT: /usr/lib/x86_64-linux-gnu/libglut.so  
** Building GLUT addon
** Cannot build ROS addon: build not using catkin
** Cannot build Matlab addon: missing Matlab
-- Looking for Q_WS_X11
-- Looking for Q_WS_X11 - found
-- Looking for Q_WS_WIN
-- Looking for Q_WS_WIN - not found
-- Looking for Q_WS_QWS
-- Looking for Q_WS_QWS - not found
-- Looking for Q_WS_MAC
-- Looking for Q_WS_MAC - not found
-- Found Qt4: /usr/bin/qmake-qt4 (found version "4.8.7") 
-- Checking for module 'tinyxml'
--   Found tinyxml, version 2.6.2
-- Checking for module 'muparser'
--   Found muparser, version 2.2.3
-- Checking for module 'ode'
--   Found ode, version 0.14
** Building odesim addon
-- Compiler version: -c++
-- Found Qt4: /usr/bin/qmake-qt4 (found version "4.8.7") 
** Building RBDL addon
-- No valid environment variable 'SUITE_DIR' found, using built-in search paths.
-- No valid environment variable 'PACKAGES_DIR' found. using built-in search paths.
-- Looking for packages in '/lib64'
-- Looking for packages in '/usr/local/lib64'
-- Looking for packages in '/usr/share'
-- Looking for packages in '/usr/local/share'
-- Looking for packages in '/lib'
-- Looking for packages in '/usr/lib'
-- Looking for packages in '/usr/local/lib'
-- Looking for packages in '/opt'
-- Looking for MUSCOD
-- MUSCOD-II not found
-- Found Qt4: /usr/bin/qmake-qt4 (found version "4.8.7") 
** Building leosim addon
-- Checking for one of the modules 'libftdipp;libftdipp1'
-- Looking for sb02od_ in slicot
-- Looking for sb02od_ in slicot - not found
-- ZeroMQ version: 4.2.5
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread (found version "3.0.0") 
** Building ZeroMQ addon
-- ZeroMQ version: 4.2.5
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread;-lpthread (found version "3.0.0") 
-- Looking for TF_Version in tensorflow
-- Looking for TF_Version in tensorflow - not found
** Cannot build TensorFlow addon: missing one of {protobuf, tensorflow-c-api}
CMake Warning at addons/box2d/build.cmake:4 (FIND_PACKAGE):
  By not providing "FindBox2D.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Box2D", but
  CMake did not find one.

  Could not find a package configuration file provided by "Box2D" with any of
  the following names:

    Box2DConfig.cmake
    box2d-config.cmake

  Add the installation prefix of "Box2D" to CMAKE_PREFIX_PATH or set
  "Box2D_DIR" to a directory containing one of the above files.  If "Box2D"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  grl.cmake:39 (include)
  CMakeLists.txt:76 (grl_build_library)


** Cannot build Box2D addon: missing box2d
** Building Python addon
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- LTO enabled
CMake Warning (dev) at base/link.cmake:1 (target_link_libraries):
  Policy CMP0023 is not set: Plain and keyword target_link_libraries
  signatures cannot be mixed.  Run "cmake --help-policy CMP0023" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  The keyword signature for target_link_libraries has already been used with
  the target "grlpy".  All uses of target_link_libraries with a target should
  be either all-keyword or all-plain.

  The uses of the keyword signature are here:

   * externals/pybind11/tools/pybind11Tools.cmake:107 (target_link_libraries)

Call Stack (most recent call first):
  grl.cmake:23 (include)
  addons/python/build.cmake:32 (grl_link_libraries)
  grl.cmake:39 (include)
  CMakeLists.txt:76 (grl_build_library)
This warning is for project developers.  Use -Wno-dev to suppress it.

** Building LCI addon
-- The Fortran compiler identification is unknown
-- Configuring done
-- Generating done
-- Build files have been written to: /home/rov/grl/build

**Comment by wcaarls** [comment]
I think it should resolve itself if you run cmake again in the same directory. However, try this version: 
43c64a4

**Comment by salvato** [comment]
Solved. Rerunning cmake ..  and then make, after the error solved the problem.
Thank you very much
